services:
  sacron_backend:
    build:
      context: .
    image: sacron_backend:latest
    container_name: sacron_backend_container
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pm2", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
